---
name: Build And Deploy (US-WEST-2)
on:
  push:
    branches: [main, multi-region-deploy]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs: # We need two separate builds as each is going to a different ECR repo
  build-prod:
    permissions:
      packages: write
      id-token: write
    uses: ipfs-elastic-provider/shared-workflows/.github/workflows/lambda-shared-build.yaml@main
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: us_west_2
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_US_WEST_2_PROD }}
  deploy-to-prod:
    uses: ipfs-elastic-provider/shared-workflows/.github/workflows/lambda-shared-deploy.yaml@main
    permissions:
      id-token: write
    needs: build-prod
    with:
      deploy_to_environment: prod
      lambda: bucket-to-indexer
      docker_image_version: ${{ needs.build-prod.outputs.build_date }}
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: us_west_2
      aws_ecr_repository: ${{ secrets.AWS_ECR_REPOSITORY_US_WEST_2_PROD }}
