name: PR Build
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    permissions:
      id-token: write
    uses: ipfs-elastic-provider/shared-workflows/.github/workflows/lambda-shared-build.yaml@main
    with:
      docker_push: false
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      aws_role_id: ${{ secrets.AWS_ROLE_ID }}
      aws_region: us-west-2
      aws_ecr_repository: any

